import random

SCREEN_HEIGHT = 600
SCREEN_WIDTH = 800

P1_STARTING_POS = (-350, 0)
P2_STARTING_POS = ((P1_STARTING_POS[0]*-1), 0)

PADDLE_MOV_DISTANCE = 20

BALL_STARTING_DIRECTION = random.randrange(1, 359)
while BALL_STARTING_DIRECTION == 90 or BALL_STARTING_DIRECTION == 180 or BALL_STARTING_DIRECTION == 270:
    BALL_STARTING_DIRECTION = random.randrange(1, 359)

BALL_STARTING_SPEED = 10